import './globals.css'
import { personalData,aboutMe, skills,professionalData } from '@/data/page-data'
import SideBar from './components/sideBar'
import Footer from './components/footer'
import Header from './components/header'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body >
      
       <Header/>
        {children}
         <Footer/>
      </body>
     
    </html>
  )
}
